language: scala
scala:
- 2.11
- 2.12
jdk:
- oraclejdk10
- openjdk10
notifications:
  email:
    recipients:
    - francois@univalence.io
    - jonathan@univalence.io
    - philippe@univalence.io
  slack: univalence:MKOquQ7wRX5BDPuwGhct0zms

script:
  - sbt "+ clean" coverage "+ test" coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)